spring:
  datasource:
    url: jdbc:mysql://localhost:3307/SpringBooM?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    
#JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
